///////////////////////////////////////////////////////////
//  GiaodichTiente.cs
//  Implementation of the Class GiaodichTiente
//  Generated by Enterprise Architect
//  Created on:      17-Sep-2026 9:35:26 PM
//  Original author: Admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class GiaodichTiente {

	private double Tygia;
	private string LoaitienTe;



	~GiaodichTiente(){

	}

	public GiaodichTiente(){

	}

	public double ThanhTien(){

		return 0;
	}

}//end GiaodichTiente