///////////////////////////////////////////////////////////
//  GiaodichVang.cs
//  Implementation of the Class GiaodichVang
//  Generated by Enterprise Architect
//  Created on:      17-Sep-2026 9:35:27 PM
//  Original author: Admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class GiaodichVang {

	private string Loaivang;



	~GiaodichVang(){

	}

	public GiaodichVang(){

	}

	public double ThanhTien(){

		return 0;
	}

}//end GiaodichVang