///////////////////////////////////////////////////////////
//  Giaodich.cs
//  Implementation of the Class Giaodich
//  Generated by Enterprise Architect
//  Created on:      17-Sep-2026 9:35:25 PM
//  Original author: Admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Giaodich {

	private string Magiaodich;
	private Datetime Ngaygiaodich;
	private double Dongia;
	private int Soluong;



	~Giaodich(){

	}

	public Giaodich(){

	}

	public double Thanhtien(){

		return 0;
	}

}//end Giaodich