///////////////////////////////////////////////////////////
//  SinhVienTrungCap.cs
//  Implementation of the Class SinhVienTrungCap
//  Generated by Enterprise Architect
//  Created on:      18-Sep-2026 6:50:16 PM
//  Original author: Admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Bài06;
namespace Bài06 {
	public class SinhVienTrungCap : SinhVien {

		private int thoigianDaotao;

		public SinhVienTrungCap(){

		}

		~SinhVienTrungCap(){

		}

	}//end SinhVienTrungCap

}//end namespace Bài06