///////////////////////////////////////////////////////////
//  SinhVienLienKet.cs
//  Implementation of the Class SinhVienLienKet
//  Generated by Enterprise Architect
//  Created on:      18-Sep-2026 6:50:14 PM
//  Original author: Admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Bài06;
namespace Bài06 {
	public class SinhVienLienKet : SinhVien {

		private string quocGia;

		public SinhVienLienKet(){

		}

		~SinhVienLienKet(){

		}

	}//end SinhVienLienKet

}//end namespace Bài06