///////////////////////////////////////////////////////////
//  SinhVienDaiHoc.cs
//  Implementation of the Class SinhVienDaiHoc
//  Generated by Enterprise Architect
//  Created on:      18-Sep-2026 6:50:13 PM
//  Original author: Admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Bài06;
namespace Bài06 {
	public class SinhVienDaiHoc : SinhVien {

		private string detaiTN;

		public SinhVienDaiHoc(){

		}

		~SinhVienDaiHoc(){

		}

	}//end SinhVienDaiHoc

}//end namespace Bài06