///////////////////////////////////////////////////////////
//  SinhVienCaoDang.cs
//  Implementation of the Class SinhVienCaoDang
//  Generated by Enterprise Architect
//  Created on:      18-Sep-2026 6:50:12 PM
//  Original author: Admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using bài06;
namespace bài06 {
	public class SinhVienCaoDang : SinhVien {

		private string chuyenNganh;

		public SinhVienCaoDang(){
			chuyenNganh = ";"
		}

		public	SinhVienCaoDang(){

		}

	}//end SinhVienCaoDang

}//end namespace Bài06